#!/usr/bin/env bash

echo "Setting up your environment..."

red() {
  echo -e "\033[31m $1\033[0m"
}

green() {
  echo -e "\033[0;32m$1\033[0m"
}

white() {
  echo -e "\033[0;37m$1\033[0m"
}

command_exists() {
  command -v "$1" &>/dev/null
}

test_dependency() {
  if command_exists "$1"; then
    green "  ✔  $2 is already installed."
  else
    exec >&2
    red "   ✖  You need to install $2.\c"
    if [[ -n "$3" ]]; then
      white "\n     $3\n"
    else
      echo " If you use Homebrew, you can run:"
      white "     brew install $2\n"
    fi
    return 1
  fi
}

check_ruby() {
  if ruby -v | grep -q "$1"; then
    green "  ✔  Ruby $1 is already installed."
  else
    red "  ✖  Ruby $1 is not installed. Please install it."
    return 1
  fi
}

(
  set -e
  check_ruby "2.1.2"
  test_dependency "bundle" "Bundler" "gem install bundler"
  test_dependency "rubocop" "rubocop" "gem install rubocop"
  test_dependency "overcommit" "overcommit" "gem install overcommit"
)

if (( $? != 0 )); then
  exit $?
fi

echo "Installing gems"
bundle check || bundle install --quiet

echo "Copying sample files"
for sample in $(find config -maxdepth 2 -type f  -name '*.sample'); do
  if [[ -f "$sample" ]]; then
    cp "$sample" "${sample%.*}"
  fi
  echo "    $sample"
done

if tty -s; then
  echo "Installing overcommit hooks"
  overcommit --install
fi

echo "Setup development database"
bundle exec rake db:setup &&

echo "Done"
